# Site settings
title: AydenKoans
email: jessyplemire@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Maths, physics, Rust dev and all these other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jadpole.github.io" # the base hostname & protocol for your site
# witter_username: jekyllrb
github_username:  jadpole

# Build settings
markdown: redcarpet

permalink: "/:year/:y-day/:title.html"